name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pipeline: [rnaseq, viralrecon, ampliseq]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install Nextflow
        run: |
          curl -s https://get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/nextflow

      - name: Run smoke test
        env:
          PIPELINE_KEY: ${{ matrix.pipeline }}
          NXF_ENABLE_FUSION: 'true'
        run: |
          set -euo pipefail
          source common/versions.env
          case "$PIPELINE_KEY" in
            rnaseq)
              WF=nf-core/rnaseq
              TAG=$RNASEQ
              PIPELINE_NXF_VERSION=25.04.7
              ;;
            viralrecon)
              WF=nf-core/viralrecon
              TAG=$VIRALRECON
              PIPELINE_NXF_VERSION=25.04.7
              ;;
            ampliseq)
              WF=nf-core/ampliseq
              TAG=$AMPLISEQ
              PIPELINE_NXF_VERSION=24.04.4
              ;;
            *)
              echo "Unknown pipeline $PIPELINE_KEY" >&2
              exit 1
              ;;
          esac
          PARAMS=pipelines/${PIPELINE_KEY}/params/toy.json
          OUTDIR=runs/${PIPELINE_KEY}-ci
          export NXF_VERSION=${NXF_VERSION:-$PIPELINE_NXF_VERSION}
          nextflow run "$WF" \
            -c common/nextflow.config \
            -r "$TAG" \
            -profile test,docker \
            --params-file "$PARAMS" \
            --outdir "$OUTDIR"

      - name: Upload smoke outputs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.pipeline }}-runs
          path: runs/${{ matrix.pipeline }}-ci
          retention-days: 5
